config/routes.rb
Umdigito::Application.routes.draw do
  
     root :to => 'homes#index'
     resources :comerciais
     resources :gerenciais
     resources :administradores
    

  
 
end

app/controllers/administradores_controller.rb
class AdministradoresController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comerciais_controller.rb
class ComerciaisController < ApplicationController
  def index
  end
end

app/controllers/gerenciais_controller.rb
class GerenciaisController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/administradores_helper.rb
module AdministradoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comerciais_helper.rb
module ComerciaisHelper
end

app/helpers/comercial_helper.rb
module ComercialHelper
end

app/helpers/gerenciais_helper.rb
module GerenciaisHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/administradores/index.html.erb
<div class="container">
<div class="content">


<div id="latestnews">
<h2>Sistema Administrador Geração 4</h2>
<ul>
<li>
<div class="imgholder"><a href="http://www.digisat.com.br/ftp/apresentacoes/ADMINISTRADOR.swf" target="_blank" title="Acesse a demostração do sistema"> <%= image_tag "1312582664_catalogo.jpg", :size => "135x135" %></a></div>
<div class="latestnews">
<h2>Sistema de Administrador Completo!</h2>
<p>Os produtos DigiSat são o resultado da combinação de tecnologia e inteligência com o objetivo da otimização de recursos, ampliação de seus negócios, relacionamento e automação de processos empresariais.

A DigiSat fornece ao mercado soluções em software para micro e pequenas empresas, fáceis, funcionais, seguras e modernas.

Isso gera maior competitividade e permitem tranquilidade no gerenciamento de seu negócio.</p>
<p class="readmore"><a href="http://www.digisat.com.br/ftp/apresentacoes/ADMINISTRADOR.swf" target="_blank" title="Acesse a demostração do sistema">Demostração &raquo;</a></p>
</div>
<br class="clear" />
</li>

</ul>
</div>
<!-- tela 1 -->
<div id="topstory">
<h2>Telas do Sistema Administrador 4</h2>
<ul>
<li>
 <a href="<%= image_path 'a2.jpg' %>" rel="lightbox"  > 
    	<%= image_tag 'a2.jpg',:size => "190x140" %>  
      </a>


</li>
<li> <a href="<%= image_path 'a3.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'a3.jpg',:size => "190x140" %>  
      </a>


</li>
<li class="last"> <a href="<%= image_path 'a4.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'a4.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 2 -->
<div id="topstory">

<ul>
<li> <a href="<%= image_path 'a5.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'a5.jpg',:size => "190x140" %>  
      </a>          

</li>
<li> <a href="<%= image_path 'a6.png' %>" rel="lightbox"  > 
        <%= image_tag 'a6.png',:size => "190x140" %>  
      </a>

</li>
<li class="last"> <a href="<%= image_path 'a7.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'a7.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 2 -->
<!-- tela 3 -->
<div id="topstory">

<ul>
<li> <a href="<%= image_path 'a8.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'a8.jpg',:size => "190x140" %>  
      </a>       

</li>
<li> <a href="<%= image_path 'a9.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'a9.jpg',:size => "190x140" %>  
      </a>

</li>
<li class="last"> <a href="<%= image_path 'a10.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'a10.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 3 -->
<!--visao geral -->
<div id="latestnews">
<h2>Visão Geral do Sistema</h2>
<ul>
<li>

<div class="latestnewsgeral">

<p>
   <h3>MÓDULO COMERCIAL</h3>

        SGBD Firebird 2.0 (segurança e eficiência).<br>
        Atende à legislação vigente.<br>
        PAF-ECF homologado.<br>
        NF-e 2.0, sem custo adicional.<br>
        Permite emissão da NF-e em vários terminais.<br>
        Multi-usuário.<br>
        Estrutura de desenvolvimento robusta.<br>
        Ferramentas de backup automático e programável.<br>
        Acesso aos módulos por senha, com níveis de acesso.<br>
        Gerador de inventário.<br>
        Módulo para gestão de valores (Gestão Empresarial).<br>
        Controle de clientes, fornecedores, estoque e transportadoras (ficha configurável).<br>
        Cálculo automático do preço de venda.<br>
        Bloqueio de venda através do limite de crédito do cliente.<br>
        Controle de vendedores com comissão.<br>
        Módulo para alteração rápida de preços do estoque.<br>
        Pedido de venda e compra.<br>
        Compras e importação do XML do fornecedor.<br>
        Consulta CNPJ no site da Receita Federal.<br>
        Cotação de compras.<br>
        Vendas (nota fiscal de produtos, serviços, venda balcão).<br>
        Envio de e-mail de orçamentos, cotação, pedidos, NF-e e débitos de clientes.<br>
        Atualização automática do preço de venda.<br>
        Preço diferenciado para revenda, consumidor e produtos em promoção.<br>
        Preço mínimo de venda por produto e limite de desconto.<br>
        Controle de produtos em consignação.<br>
        Grade, kit, composição, grupos em níveis, seriais e foto de produtos.<br>
        Leitura por código de barras ou sequencial.<br>
        Rotatividade dos produtos.<br>
        Controle de empresas conveniadas.<br>
        Posição financeira e comercial do cliente e do fornecedor.<br>
        Controle do limite de crédito.<br>
        Gera código de barras do produto.<br>
        Simulador de preço a prazo.<br>
        Tabela de preços.<br>
        Possibilidade de ocultar o preço de custo nos módulos.<br>
        Controle de contatos mantidos com os clientes.<br>
        Possibilidade de bloquear o acesso à orçamentos, pedidos e ordens de serviço já faturadas.<br>
        Consulta a situação de clientes e fornecedores.<br>
        SPED Fiscal, EFD Contribuições e Sintegra.<br>
        Gerador de relatórios.<br>
        Módulo de controle de entrega de mercadorias.<br>
<br>
<h3>MÓDULO  FINANCEIRO</h3>

        Controle de caixa com plano de contas, centro de custos e balancete.<br>
        Contas à pagar e à receber.<br>
        Módulo para recebimento rápido de contas à receber.<br>
        Controle de bancos e lançamentos bancários.<br>
        Boletos bancários impressos em dois modelos ou remessa/retorno.<br>
        Importação de extratos bancários.<br>
        Impressão de cheques, bloquetos, duplicatas, etc...<br>
        Fluxo de caixa futuro (previsão diária).<br>
        Posição dos lançamentos (recebidos, em atraso e a receber).<br>
        Consulta prática de lançamentos à pagar e receber no dia.<br>
        Módulo de controle de cheques recebidos, emitidos e repassados, com consulta de situação.<br>
<br>
<h3>MÓDULO DE  SERVIÇOS</h3>

        Controle de ordens de serviço (DAV-OS).<br>
        Cadastro de objetos e técnicos.<br>
        Cadastro de serviços no estoque (conforme orientação PAF-ECF).<br>
        Ordens de serviço organizadas por categorias e tipos de atendimentos.<br>
        Envio de ordens de serviço por e-mail.<br>
        Posição das ordens de serviço fechadas e em andamento.<br>
        Busca de ordens de serviço através da placa/serial do objeto.<br>

<br>
 <h3>MÓDULO INDÚSTRIA</h3>

        Cadastro de funcionários, com indicação de jornada de trabalho, cargo e setor de atuação.<br>
        Cadastro de lotes de produtos produzidos.<br>
        Produtos produzidos separados em grupos, configuráveis em níveis.<br>
        Desmembramento de produtos.<br>
        Entrada no estoque de produtos produzidos.<br>
        Saída de matéria-prima do estoque.<br>
        Controle de fases de produção, por produto produzido e por matéria-prima.<br>
        Cadastros de custos de produção configurável, por produto.<br>
        Cálculo de custo de produção considerando custos configurados nos produtos, encargos sociais, mão de obra direta e custos indiretos.<br>
        Simulador de custos da produção, por produto.<br>
        Controle de programação de produção da fábrica com simulador.<br>
        Visualização de data e hora previstos para início e término da programação, considerando as datas das programações antecessoras.<br>

</p>
<p class="readmore"><a href="http://www.digisat.com.br/ftp/apresentacoes/ADMINISTRADOR.swf" target="_blank" title="Acesse a demostração do sistema">Demostração &raquo;</a></p>
</div>
<br class="clear" />
</li>

</ul>
</div>
<!--visao geral -->

</div>
<div class="column">

<%= render "layouts/publicidade" %>

</div>
<br class="clear" />
</div>

app/views/comerciais/index.html.erb
<div class="container">
<div class="content">


<div id="latestnews">
<h2>Sistema Comercial</h2>
<ul>
<li>
<div class="imgholder"><a href="http://www.digisat.com.br/ftp/apresentacoes/SISTEMACOMERCIAL.swf" target="_blank" title="Acesse a demostração do sistema"> <%= image_tag "1312590567_catalogo.jpg", :size => "135x135" %></a></div>
<div class="latestnews">
<h2>Sistema de Frente de Caixa completo!</h2>
<p>Os produtos DigiSat são o resultado da combinação de tecnologia e inteligência com o objetivo da otimização de recursos, ampliação de seus negócios, relacionamento e automação de processos empresariais.

A DigiSat fornece ao mercado soluções em software para micro e pequenas empresas, fáceis, funcionais, seguras e modernas.

Isso gera maior competitividade e permitem tranquilidade no gerenciamento de seu negócio.</p>
<p class="readmore"><a href="http://www.digisat.com.br/ftp/apresentacoes/SISTEMACOMERCIAL.swf" target="_blank" title="Acesse a demostração do sistema">Demostração &raquo;</a></p>
</div>
<br class="clear" />
</li>

</ul>
</div>
<!-- tela 1 -->
<div id="topstory">
<h2>Telas do Sistema Comercial</h2>
<ul>
<li>
 <a href="<%= image_path 'tela01.jpg' %>" rel="lightbox"  > 
    	<%= image_tag 'tela01.jpg',:size => "190x140" %>  
      </a>


</li>
<li> <a href="<%= image_path 'tela02.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela02.jpg',:size => "190x140" %>  
      </a>


</li>
<li class="last"> <a href="<%= image_path 'tela03.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela03.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 2 -->
<div id="topstory">

<ul>
<li> <a href="<%= image_path 'tela04.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela04.jpg',:size => "190x140" %>  
      </a>          

</li>
<li> <a href="<%= image_path 'tela05.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela05.jpg',:size => "190x140" %>  
      </a>

</li>
<li class="last"> <a href="<%= image_path 'tela06.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela06.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 2 -->
<!-- tela 3 -->
<div id="topstory">

<ul>
<li> <a href="<%= image_path 'tela07.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela07.jpg',:size => "190x140" %>  
      </a>       

</li>
<li> <a href="<%= image_path 'tela08.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela08.jpg',:size => "190x140" %>  
      </a>

</li>
<li class="last"> <a href="<%= image_path 'tela01.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'tela01.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 3 -->
<!--visao geral -->
<div id="latestnews">
<h2>Visão Geral do Sistema</h2>
<ul>
<li>

<div class="latestnewsgeral">

<p>
    Atende requisitos da legislação vigente (PAF-ECF - Ato Cotepe 06/08).<br>
    Emissão de cupom fiscal (ECF).<br>
    Emissão de relatórios gerenciais.<br>
    Controle de estoque com baixa on line.<br>
    Retaguarda com faturamento.<br>
    Contas a receber, compras e inventário.<br>
    <a href="http://www.digisat.com.br/produtos-ver.php?produto=2" target="_blank" title="Veja no site da Digisat"> Suporta várias impressoras fiscais (lista em nosso site).</a><br>
    Display torre.<br>
    TEF discado e dedicado.<br>
    Gaveta de dinheiro.<br>
    Teclado reduzido com ou sem visor.<br>
    Uso simultâneo do leitor de barras e teclado.<br>
    Suporte a balanças checkout e etiquetadora.<br>
    Gera Sintegra, mapa resumo e SPED Fiscal.<br>
    Permite apresentar a foto do produto.<br>
    Apresentação de mensagem promocional.<br>
    Mensagem de rodapé padrão.<br>
    Grade de quantidade.<br>
    Consulta de preços na venda.<br>
    Sangria ou suprimento.<br>
    Leitura X e Redução Z.<br>
    Leitura de memória fiscal em papel ou arquivo.<br>
    Inclusão de totalizadores não fiscais.<br>
    Desconto automático com controle de empresas conveniadas.<br>
    Venda a prazo com impressão das condições no cupom.<br>
    Prazo com opção de código de barras.<br>
    Cancelamento por item ou cupom.<br>
    Controle e impressão de cheques e cartões.<br>
    Pagamento de cupom com várias espécies.<br>
    Controle de permissões para operadores de caixa.<br>
    Permite utilizar os Sistemas Administrador ou Gerencial G4 como retaguarda.<br>
    Suporte a skins para customização do sistema.<br>
    Recebimento de parcelas pagas no caixa.<br>
    Identificação do consumidor no cupom.<br>
    Indexador de preços.<br>
    Possibilita utilização de monitores touch-screen.<br>
    CNPJ/CPF do consumidor no cupom.<br>
    Acréscimo ou desconto por item vendido ou no total da venda.<br>
    Possibilita a inclusão de Espécies de recebimentos.<br>
    Recebimento de contas.<br>
    Proteção contra queda de energia.<br>
    NF-e integrada.
</p>
<p class="readmore"><a href="http://www.digisat.com.br/ftp/apresentacoes/SISTEMACOMERCIAL.swf" target="_blank" title="Acesse a demostração do sistema">Demostração &raquo;</a></p>
</div>
<br class="clear" />
</li>

</ul>
</div>
<!--visao geral -->

</div>
<div class="column">

<%= render "layouts/publicidade" %>

</div>
<br class="clear" />
</div>

app/views/gerenciais/index.html.erb
<div class="container">
<div class="content">


<div id="latestnews">
<h2>Sistema Gerencial Geração 4</h2>
<ul>
<li>
<div class="imgholder"><a href="http://www.digisat.com.br/ftp/apresentacoes/GERENCIAL.swf" target="_blank" title="Acesse a demostração do sistema"> <%= image_tag "1312589759_catalogo.jpg", :size => "135x135" %></a></div>
<div class="latestnews">
<h2>Sistema de Frente de Caixa e Retaguarda Completo!</h2>
<p>O Sistema Gerencial G4 atende a micro e pequena empresa, atuando na retaguarda, serviços e frente de caixa, através do Sistema Comercial G4, embutido no pacote.

Permite realizar os processos de automação comercial de forma integrada e eficiente, agilizando o atendimento aos clientes, e garantindo o gerenciamento completo da empresa.</p>
<p class="readmore"><a href="http://www.digisat.com.br/ftp/apresentacoes/GERENCIAL.swf" target="_blank" title="Acesse a demostração do sistema">Demostração &raquo;</a></p>
</div>
<br class="clear" />
</li>

</ul>
</div>
<!-- tela 1 -->
<div id="topstory">
<h2>Telas do Sistema Gerencial 4</h2>
<ul>
<li>
 <a href="<%= image_path 'g02.jpg' %>" rel="lightbox"  > 
    	<%= image_tag 'g02.jpg',:size => "190x140" %>  
      </a>


</li>
<li> <a href="<%= image_path 'g03.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g03.jpg',:size => "190x140" %>  
      </a>


</li>
<li class="last"> <a href="<%= image_path 'g04.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g04.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 2 -->
<div id="topstory">

<ul>
<li> <a href="<%= image_path 'g05.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g05.jpg',:size => "190x140" %>  
      </a>          

</li>
<li> <a href="<%= image_path 'g06.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g06.jpg',:size => "190x140" %>  
      </a>

</li>
<li class="last"> <a href="<%= image_path 'g07.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g07.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 2 -->
<!-- tela 3 -->
<div id="topstory">

<ul>
<li> <a href="<%= image_path 'g08.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g08.jpg',:size => "190x140" %>  
      </a>       

</li>
<li> <a href="<%= image_path 'g09.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g09.jpg',:size => "190x140" %>  
      </a>

</li>
<li class="last"> <a href="<%= image_path 'g10.jpg' %>" rel="lightbox"  > 
        <%= image_tag 'g10.jpg',:size => "190x140" %>  
      </a>

</li>
</ul>
<br class="clear" />
</div>
<!-- tela 3 -->
<!--visao geral -->
<div id="latestnews">
<h2>Visão Geral do Sistema</h2>
<ul>
<li>

<div class="latestnewsgeral">

<p>
    <h3>Atende comércio em geral.</h3>

Também atende modulos especificos, sem custo adicional:<br>

    Restaurantes<br>
    Restaurante com dispositivos móveis (MG4)<br>
    Farmácias<br>
    Prestadores de Serviços<br>
    Oficinas (Ordem de Serviços)<br><br>

 

<h3>Facilidades do Sistema Gerencial G4</h3>

- Homologado ER-PAF-ECF.<br>

- Gera NF-e, atendendo a legislação vigente. Em constante atualização.<br>

- Gera NF-e com produtos e serviços (conjugada).<br>

- Atende Restaurantes.<br>

- Restaurante permite gerenciar mesas, gerar relatórios e atender com dispositivos móveis (módulo MG4).<br>

- Permite importar pedidos de vendas, pré vendas (antigas comandas) e ordens de serviços ao ECF.<br>

- Gera Pedidos de Venda e de Compra.<br>

- Gera inventários, exportando-os em vários formatos, inclusive XML.<br>

- Gera SPED Fiscal, EFD Contribuições e Sintegra. Em constante atualização.<br>

- Módulo de Gestão Empresarial, que permite o gerenciamento financeiro da empresa.<br>

- Permite importar o XML do fornecedor no modulo de Compras.<br>

- Controle financeiro, com contas a receber, pagar, livro caixa, bancos, boletos bancários.<br>

- Controles bancários com remessa e retorno OFC e OFX.<br>

- Muito mais...
</p>
<p class="readmore"><a href="http://www.digisat.com.br/ftp/apresentacoes/GERENCIAL.swf" target="_blank" title="Acesse a demostração do sistema">Demostração &raquo;</a></p>
</div>
<br class="clear" />
</li>

</ul>
</div>
<!--visao geral -->

</div>
<div class="column">

<%= render "layouts/publicidade" %>

</div>
<br class="clear" />
</div>

app/views/homes/index.html.erb
 <div class="container">
    <div class="content">
      <div id="topstory">
        <h2>Automação Comercial</h2>
        <ul>
          <li><%= link_to administradores_path do %> <%= image_tag '1312582664_catalogo.jpg',:size => "190x140" %><% end %>
            <p>O melhor sistema para controle físico e financeiro para sua empresa.<br>
Atende comércio em geral.<br>
Módulos específicos para: Indústrias, Prestadores de Serviços,  Supermercados<br>
Indústrias: Pequenas indústrias de fabricação em série. Controle de produção e de estoque, com cálculo de mão de obra direta e indireta embutido no custo do produto final, feito diretamente no sistema.<br>

Comércio em geral: Atende a empresas de pequeno porte em todos os ramos de comércio varejista que necessitem de sistema de automação comercial que possua robustez e controles integrados, este é o sistema que você esperava. 
</p>
            <p class="readmore"><%= link_to  administradores_path do %>Continue Lendo &raquo;<% end %></p>
          </li>
          <li><%= link_to  comerciais_path do %><%= image_tag '1312590567_catalogo.jpg',:size => "190x140" %><% end %>
             <p>Modernidade e eficiência em automação comercial.<br>

Permite a emissão de cupom fiscal e processar todas as funções pertinentes a essa função, adequadas ao que orienta a legislação ER-PAF-ECF.<br>

Pode ser utilizado sozinho ou como PDV dos retaguardas Sistema Administrador G4 ou Sistema Gerencial G4.<br>
Indicado para pequenas e micro empresas de comércio em geral.<br>

Lojas de informática, comércio de tintas, cosmésticos e perfumarias, confecções, calçados, papelaria, bicicletarias, auto elétricas, lojas de cd, livrarias, joalherias, lojas de conveniência, lojas de móveis, mercadinhos, etc.<br></p>
            <p class="readmore"><%= link_to  comerciais_path do %>Continue Lendo &raquo;<% end %></p>
          </li>
          <li class="last"><%= link_to  gerenciais_path do %><%= image_tag '1312589759_catalogo.jpg',:size => "190x140" %><% end %>
           <p>O gerente que sua empresa estava esperando.<br>

Atende comércio em geral e modulos especificos, sem custo adicional!

    Restaurantes, Restaurantes com dispositivos móveis (MG4), 
    Prestadores de Serviços, 
    Oficinas (com Ordem de Serviços), 
    Farmácias<br>
Comércio em geral: Lojas de informática, materiais de construção, comércio de tintas, cosmésticos e perfumarias, drogarias, confecções, papelarias, bicicletarias, auto elétricas, lojas de calçados, livrarias, lojas de conveniência, lojas de móveis, óticas, distribuidoras, ferragens, restaurantes, mercados, postos de combustível, prestadoras de serviço em geral, etc.</p>
            <p class="readmore"><%= link_to  gerenciais_path do %>Continue Lendo &raquo;<% end %></p>
          </li>
        </ul>
        <br class="clear" />
      </div>
      <div id="latestnews">
        <h2>Serviços Diversos</h2>
        <ul>
          <li>
            <div class="imgholder"><%= image_tag "manutencaocomputador.png" %></div>
            <div class="latestnews">
              <h2>Criação de Sites</h2>
              <p>Nossos serviços de criação de sites, ajuda sua empresa a se destacar na Internet, com qualidade e profissionalismo, entregamos cada projeto com o que a de melhor em tecnologia, posicionamos seu site nos melhores buscadores do mercado com resultados.</p>
              <p class="readmore"><a href="#">Continue Lendo &raquo;</a></p>
            </div>
            <br class="clear" />
          </li>
          <li class="last">
            <div class="imgholder"><%= image_tag "criacaosites.png" %></div>
            <div class="latestnews">
              <h2>Manutenção de Computadores</h2>
              <p>Consertamos seu computador pessoal ou de sua empresa, utilizando peças de qualidade e marcas de renome. Além de fazer com que o computador volte a funcionar pela substituição de alguma peça defeituosa, também realizamos a configuração correta do hardwarer e do Sistema Operacional, para melhorar o desempenho de seu equipamento. </p>
              <p class="readmore"><a href="#">Continue Lendo &raquo;</a></p>
            </div>
            <br class="clear" />
          </li>
        </ul>
      </div>
    </div>
    <div class="column">
     <%= render "layouts/publicidade" %>


    </div>
    <br class="clear" />
  </div>

app/views/layouts/_header.html.erb
<div id="header">
<div id="topnav">
<ul>
  <li class="last"><a href="#">Sobre</a></li>
  <li><a href="#">Clientes</a></li>
<li><a href="#">Contato</a></li>
<li><a href="#">Criação</a>
<ul>
<li><a href="#">Sites</a></li>
<li><a href="#">Logomarcas</a></li>
<li><a href="#">E-mail Marketing</a></li>
</ul>
</li>
<li><a href="full-width.html">Assitência</a>
  <ul>
      <li><a href="#">Manutenção </a></li>
      <li><a href="#">Instalações</a></li>
      <li><a href="#">Recuperação de Hds</a></li>
  </ul>

</li>
<li><a href="full-width.html">Automação</a>
<ul>
      <li><%= link_to comerciais_path do %>
        S Comercial<% end %></li>
      <li><%= link_to gerenciais_path do %>
        S Gerencial<% end %></li>
      <li><%= link_to administradores_path do %>
        S Administrador<% end %></li>
       <li><a href="#">Produtos</a></li>
  </ul>



</li>

<li><a href="style-demo.html">Blog</a></li>
<li class="active"><%= link_to root_path do %>
Home<% end %></li></li>
</ul>
</div>
<div id="logo">

<%= link_to root_path do %>
<%= image_tag "novalogoface.png", :size =>"210x100" %>
<% end %>


</div>
<br class="clear" />
</div>

app/views/layouts/_publicidade.html.erb
<div class="sponsors">
<h2>Publicidade</h2>
<div class="b_250"><script type="text/javascript">
bb_bid = "1680108";
bb_lang = "pt-BR";
bb_name = "custom";
bb_limit = "4";
bb_format = "bbm";
</script>
<script type="text/javascript" src="http://static.boo-box.com/javascripts/embed.js"></script></div>
<div class="b_125">
<ul>
<li><a href="#"><img src="images/demo/125x125.gif" alt="" /></a></li>
<li><a href="#"><img src="images/demo/125x125.gif" alt="" /></a></li>
<li><a href="#"><img src="images/demo/125x125.gif" alt="" /></a></li>
<li><a href="#"><img src="images/demo/125x125.gif" alt="" /></a></li>
<li><a href="#"><img src="images/demo/125x125.gif" alt="" /></a></li>
<li class="last"><a href="#"><img src="images/demo/125x125.gif" alt="" /></a></li>
</ul>
<div class="clear"></div>
</div>
</div>

app/views/layouts/_slider.html.erb
 <div id="featured_slide">
    <div class="featured_box">
      
      <p class="readmore"><a href="#">Continue Lendo &raquo;</a></p>
      <%= image_tag "gerencial.jpg" %> </div>
    <div class="featured_box">
     
      <p class="readmore"><a href="#">Continue Lendo &raquo;</a></p>
        <%= image_tag "comercial.jpg" %> </div>
    <div class="featured_box">
     
      <p class="readmore"><a href="#">Continue Lendo &raquo;</a></p>
       <%= image_tag "administrador.jpg" %> </div>
    <div class="featured_box">
     
      <p class="readmore"><a href="#">Continue Lendo &raquo;</a></p>
       <%= image_tag "banner_notebook.png" %> </div>
    <div class="featured_box">
     
      <p class="readmore"><a href="#">Continue Lendo &raquo;</a></p>
      <%= image_tag "banner_computador.png" %></div>
  </div>